<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <Product>UmbracoExternalStorageWithMongoDB</Product>
    <PackageId>UmbracoExternalStorageWithMongoDB</PackageId>
	<PackageProjectUrl>https://github.com/prmeyn/UmbracoExternalStorageWithMongoDB/</PackageProjectUrl>
	<Description>
		This package allows you to store your custom data in a NoSQL MongoDB database from Umbraco 17, using MongoDbService.
		Unlike most NoSQL databases, a MongoDB server can be installed on almost any platform, your laptop or on a Cloud service like AWS, GCP or Azure. It avoids vendor lock in into any specific hosting platform.
	</Description>
    <PackageTags>umbraco plugin package umbraco-marketplace</PackageTags>
  </PropertyGroup>
	<PropertyGroup>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="LICENSE" Pack="true" PackagePath="" />
		<Content Update="umbraco-marketplace.json" Pack="false" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Core" Version="[17.0.0, 18.0.0)" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="MongoDbService" Version="10.3.1" />
	</ItemGroup>
	<PropertyGroup>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<PropertyGroup>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
		<None Include="images\icon.png" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>
